### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by catsby** [terraform-providers/terraform-provider-panos#1]
Please update the README to reflect the similar information found here:

- https://github.com/terraform-providers/terraform-provider-aws/blob/master/README.md

**Comment by shinmog** [comment]
Hey @catsby -  How are updates expected to be handled at this point?

Is it acceptable to just make rapid and frequent changes to this repo's master (then rebase stable-website from there), agile-style?  Or am I expected to make PRs for all changes?  If PRs, do I still develop on the private repo then make PRs from those changes?  Also, if PRs, who do I get reviews from?

Is the answer different if I'm updating existing features / making bug fixes vs adding new resources / data sources?

**Comment by shinmog** [comment]
Thanks for all the info, Clint!

Readme is now updated.
