### ISSUE TITLE
sat_translated_addresses format?

### ISSUE THREAD

**Issue by gliptak** [terraform-providers/terraform-provider-panos#100]
I might have missed an example in the documentation, but I'm not sure what format to use for ```sat_translated_addresses```. I tried a dash separated range, CIDRs, name for the Addresses Object, but none of those seem to have translated to the Source Translation section (on the GUI) although running ```apply``` was successful.

https://www.terraform.io/docs/providers/panos/r/panorama_nat_rule.html

Could you offer some valid (processed) ```sat_translated_addresses``` examples?

Thanks

**Comment by gliptak** [comment]
```sat_translated_addresses``` below (right now is dash separated IP (as range) for ```dynamic-ip-and-port```:
```
resource "panos_panorama_nat_rule" "mynatrule" {
    name = "mynatrule"
    device_group = "mydevicegroup"
    rulebase = "post-rulebase"
    service = "myservice"
    target {
        serial = "123456789"
    }
    source_zones = ["UNTRUST"]
    source_addresses = ["any"]
    sat_type = "dynamic-ip-and-port"
    sat_translated_addresses = ["192.z.z.z-192.z.z.y"]

    destination_zone = "UNTRUST"
    destination_addresses = ["192.x.x.x"]
    dat_type = "dynamic"
    dat_address = "zzzzz.com"
    dat_port = "443"
}
```
After a successful run, rerunning unmodified TF template still shows ```1 changed```

**Comment by shinmog** [comment]
@gliptak 

Thanks for sharing your config with me!  So the problem is that you have not specified the variable `sat_address_type`.  In your case, you want to set it to `translated-address`.  If you do that, it will work.

**Comment by gliptak** [comment]
@shinmog thank you for the pointer. adding ```sat_address_type``` allowed to set ```    sat_translated_addresses```
