### ISSUE TITLE
Feature Request - Manage VLANs

### ISSUE THREAD

**Issue by shinmog** [terraform-providers/terraform-provider-panos#145]

**Comment by pryorda** [comment]
Still no eta on this?

**Comment by shinmog** [comment]
I rely on comments / thumbs up on feature requests to prioritize them :)

**Comment by raypettersen** [comment]
This is a very important key-feature for us, so eagerly waiting for updates :-)

**Comment by pryorda** [comment]
Yep, I'm having to hack around with terraform local-exec + interface commands.
