### ISSUE TITLE
Address group Terraform Crash

### ISSUE THREAD

**Issue by stobias123** [terraform-providers/terraform-provider-panos#151]
Trying to create an address group - terraform bugged out hard.

Error output
https://hastebin.com/esuconudiq.js

What I'm trying to run.
```
provider "panos" {
  hostname = "54.212.246.212"
  username = "admin"
  password = "pass"
}

resource "panos_panorama_address_group" "example1" {
  name             = "Spoke 1 Group"
  description      = "My NTP servers"
  static_addresses = ["10.1.0.0/16"]
}

```

**Comment by shinmog** [comment]
@stobias123 

The resource you're using above is a panorama resource.  Were you trying to configure Panorama or a firewall?  If a firewall, you should be using `panos_address_group` instead of `panos_panorama_address_group`.

**Comment by stobias123** [comment]
Ahh the provider pointed at a firewall directly. My mistake.

**Comment by shinmog** [comment]
Gotcha.  Yeah, you can manage Panorama, just specify a Panorama hostname and auth creds, and use the `panos_panorama_` resources.  If it's firewall, those are all of the non-`_panorama_` resources.
