### ISSUE TITLE
Feature request: Policy based forwarding, and monitor.

### ISSUE THREAD

**Issue by raypettersen** [terraform-providers/terraform-provider-panos#152]
We just started using the provider, and we've successfully created a ipsec VPN to amazon. However, we were forced to do to two things manually:
- Create a policy based forwarding.
- Create a monitor and attach it to the PBF.

It would be awesome to get this functionality supported by terraform. We'd then be able to fully automate vpn tunnels from on-premise PAN appliances to the cloud.

I hope to see this functionality soon.

**Comment by shinmog** [comment]
@raypettersen 

Need some clarification:  when you say "create a monitor and attach it to the PBF," do you mean to enable "Monitor" in the PBF rule under the "Forwarding" tab of the PBF rule or something else?  Or do you mean you make your own Monitor Profile and then attach that to the PBF rule..?

**Comment by raypettersen** [comment]
Basically I typically have to do the following manually when creating a VPN to AWS.

```
 edit network profiles monitor-profile tunnelmonitor
 set interval 2 threshold 5 action fail-over
 top
```
```
 edit rulebase pbf rules pbf-vpn-vpn-02f5570bd1a34432d-0
  set action forward nexthop ip-address 169.254.23.125
  set action forward egress-interface tunnel.1
  set action forward monitor profile tunnelmonitor disable-if-unreachable yes ip-address 169.254.23.125
  set source 172.16.26.0/24 source-user any destination 172.31.0.0/16 application any service any
  set from zone trusted
  set disabled no
```

Everything else is supported by the terraform provder.

**Comment by shinmog** [comment]
@raypettersen 

Thanks for the detailed info!
