### ISSUE TITLE
Ordering of tags on objects should be preserved

### ISSUE THREAD

**Issue by rfc1149** [terraform-providers/terraform-provider-panos#161]
When adding tags (panos_panorama_administrative_tag) to objects such as address objects or address groups, currently it doesn't seem that the provider enforces the list order you add them in. For instance if i have an object with tags like:

```
resource "panos_poanorama_address_group" "group1" {
  ...
  tags = [
    "tag1",
    "tag2",
    "tag3",
  ]
}

```
It is not guaranteed that the tags will show up in that order when the object gets created/updated on the firewall. 

This matters because if you've assigned colors to the tags, the name of the object in panorama will turn the color of the first tag assigned to it. If the order is not preserved, this coloring doesn't work as expected. This issue is merely cosmetic, and doesn't affect the functionality of the tags, but it is nice to have as we've assigned specific meaning to certain colors so we can glance at things quickly and understand what they are.

**Comment by shinmog** [comment]
@rfc1149 

Just fyi, this is the first of a few checkins to fix this "preserve tag ordering" issue with the various `Objects` that PAN-OS has that the provider supports.
