### ISSUE TITLE
PANOS 9.X support

### ISSUE THREAD

**Issue by tgm4883** [terraform-providers/terraform-provider-panos#170]
PANOS 9 has had a few version updates now, is support for this being worked on? The Provider page suggests that only up to version 8.1 is supported

**Comment by shinmog** [comment]
There are a few new options that PAN-OS 9.0 has added that the provider does not have controls for, and some of those additions will result in changes in the provider's existing resources.  For the most part, from what I've seen, there are no breaking changes to the schema that prevents the provider from working.

New features are in active development for the provider, stay tuned...
