### ISSUE TITLE
Feature Request: security policy group resource

### ISSUE THREAD

**Issue by lampwins** [terraform-providers/terraform-provider-panos#20]
I have been trying out the panorama support 1.1.0, thanks for the hard work @shinmog!

I am afraid though, in its present form, I cannot make use of `panos_panorama_security_policies` due to the flow used in creating/updating policies. Currently, it seems the entire rulebase for a device group is deleted and recreated on an apply. I can see how this was the easy solution when thinking all policy is managed with terraform. However, I have to argue one's panorama use case is often different. In my particular case, my terraform config and state is broken down at the application and environment level. All the while, the policies created in these disparate places, all go into a small set of device groups in panorama. This is the just the nature of the firewall deployments. Plus, there is human managed policy mixed in, in some cases. Again this is just the nature of how panorama is used.

Thus, I cannot delete and rebuild a device group rulebase on each apply, because the policy is distributed across many terraform configs.

**Comment by shinmog** [comment]
Thanks :)

Are you needing the plumbing that would allow you to manage individual security policies?  Or just looking for the plumbing to add / remove serial numbers (and their vsys) to existing security policies (aka - `panos_panorama_device_group_entry`, but for Panorama security policies)?

**Comment by lampwins** [comment]
@shinmog this would be for managing individual--or subset of--policies without affecting the existing "state" of a device group in a negative way (deleting existing policies).

**Comment by btorresgil** [comment]
Hi @lampwins , good to connect with you again. If a device group has managed and unmanaged rules, what would your expectation be on how to tell terraform what order the rules should be in when they are a mix of managed and unmanaged?

Second question, would it be a reasonable approach using the current provider for you to mix managed and unmanaged rules by putting them into their own device groups and mixing them into a DG Hierarchy?  For example, DG1 has 2 children, DG2 and DG3. DG2 is not managed by terraform, DG3 is managed by terraform. So DG1 has a mix of managed and unmanaged rules.  Would this fit with what you’re trying to accomplish?  If not, can you give us a concrete example where this model doesn’t work?

Thanks!!

**Comment by lampwins** [comment]
@btorresgil I figured you might have been involved with this.

To your first question, I would not have a problem with simply adding the new policy to either the bottom or top of an existing rulebase. I imagine though, that might be specific to my use case and I acknowledge the complexity of the problem.

To your second question, the problem is, from my experience, the DG hierarchy does not work as you have described and comes with a few other limitations and considerations. The effective policy for a firewall is built by traversing the tree strictly upward from the DG the firewall is assigned to. So in your example, if the firewall was assigned to DG1, it would not receive policy from either DG2 or DG3. Similarly, if the firewall is assigned to DG2, it would not receive policy from DG3 (but would from DG1). With that in mind, here is the hierarchy I have been playing with:

<img width="401" alt="screen shot 2018-05-06 at 8 42 20 pm" src="https://user-images.githubusercontent.com/1297132/39680385-04773abe-516e-11e8-9612-497829951a14.png">

A couple things to note; the firewall is assigned to a leaf at the bottom of the tree, and we have to pay special attention to the height of the tree. As of 8.0, a max height of 4 is allowed which has real-world implications, which you can sort of see from the use of groupings like "Perimeter," etc. Second, the ordering of the groups is significant when considering the policy precedence of the hierarchy on the firewall's ruleset. In my case, I prefer to use the post-rulebase under normal circumstances (so that policy can be preempted on the local firewall). Given my use case, I want my manual policy to always preempt the automated policy, so the automated DG has to be a child of the manual DG. Now, of course, those are implementation details, but it is important to see some of the increases of the DG hierarchy.

Doing this, while certainly possible, is IMHO quite a hack of the DG hierarchy. I think the concept of a reusable "ruleset" or means to group policy outside of the DG context, would really solve all these problems. So we could have terraform target a "ruleset" and an administrator would assign that ruleset to a DG in a specific spot in the DG's rulebase. This is a concept I have brought up a couple of times before but I am not sure if an official request exists.

The other thing lurking in my comments is distributing the terraform state (the security policies in this case) across multiple terraform workspaces. First, a little bit of background on where I am coming from; the current panos terraform model works fine when dealing with individual firewalls. From the deployments I have seen, all of the policy for an individual firewall is managed in a single terraform workspace. The difference with panorama, is it is used as a means to aggregate management functionality for many firewalls. Thus, the policy for many different applications (thus terraform workspaces) all wind up pointing at panorama. However, their state is independent and in the current model, each workspace expects to handle the entirety of a rulebase, which is going to cause confict.

Does that help clear up what I was saying? Feel free to tell me I am way off base :)

**Comment by btorresgil** [comment]
@lampwins This is all @shinmog 's work, I'm just helping out with some design questions like this.  Thanks for the great details, you're right I didn't describe DG hierarchy correctly, that's what I get for replying to github issues on Sunday.  Give us a bit to digest this and we'll talk soon.  If you'll be at Ignite conference in a couple week, lets meet up and chat there too, would love to hear more about what you're doing with Terraform.

**Comment by shinmog** [comment]
@lampwins 
Thanks for taking time to chat with us at Ignite 2018, John!  Based on our discussions, I'm thinking that maybe there could exist a new resource to handle this scenario.  Well, two new resources:

`panos_security_policy_group` and `panos_panorama_security_policy_group`

These would look very much like the current `panos_security_policies` resource from a configuration perspective, but it would only manage the policies specified in the group.  The `vsys` param would still exist so you could specify a vsys.

As for group ordering as it relates to other groups, I'm thinking that I could also add two other resource params:  `place_group_above` and `place_group_below`, which would take another security policy's name, placing this group either above or below the referenced policy (only one of these could be specified).

Would this work?

**Comment by lampwins** [comment]
@shinmog Yes, it was a nice talk! I think this idea sounds great. It should work just fine for my use case. Thanks for all your hard work!

**Comment by shinmog** [comment]
This feature request has been addressed and will be included in the next provider release.

**Comment by shinmog** [comment]
@lampwins 
This is now added to the 1.2.0 provider.
