### ISSUE TITLE
IPSEC Crypto Profile Apply Failed and Crashed Terraform

### ISSUE THREAD

**Issue by jonshern** [terraform-providers/terraform-provider-panos#222]
```
resource "panos_ipsec_crypto_profile" "ipsec" {
    name = "test"
    authentications = ["sha256"]
    encryptions = ["aes-256-cbc"]
    dh_group = "group2"
    lifetime_type = "seconds"
    lifetime_value = 3600

}
```

When we try to apply this resource
Terraform crashes 
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by shinmog** [comment]
There are two types of resources:  Panorama resources and firewall resources; and you have to use the correct resource or Terraform crashes.  Are you attempting to use a firewall resource against Panorama by chance?

**Comment by jonshern** [comment]
Yeah it looks like you are right.  We used a firewall resource instead of a panorama resource.  
Thanks
