### ISSUE TITLE
panos_panorama_device_group unsupported argument "device_group"

### ISSUE THREAD

**Issue by jrd57** [terraform-providers/terraform-provider-panos#228]
Hi everyone,

I'm new here and i didn't find the properly folder to create my bug report sorry...
I would create an device group into an other device group, i used the optional argument "device_group"
But when I try to apply it's write that :

Error: Unsupported argument

  on provider.tf line 9, in resource "panos_panorama_device_group" "example":
   9:   device_group = "Datacenter_Device_Group"

An argument named "device_group" is not expected here.

my code `resource "panos_panorama_device_group" "example" {
	name = "JORD"
	device_group = "Datacenter_Device_Group"
        serial = "XXX"
}
`

Thank you

**Comment by jrd57** [comment]
Hi @ewbankkit 
> 
> 
> @jrd57 It looks like this issue should be raised in the https://github.com/terraform-providers/terraform-provider-panos repository.
> Thanks.

Did you know how i can use the code here :  
https://github.com/terraform-providers/terraform-provider-panos/blob/master/panos/resource_panorama_device_group.go

i have install his plugin but don't know how use to create device group on an other device group  hierarchy.

Thanks

**Comment by shinmog** [comment]
@jrd57 

If you're trying to create a device group, then the param name is `name` (you specify the device group using `device_group` in other Panorama resources).  Please refer to the documentation here:  https://www.terraform.io/docs/providers/panos/r/panorama_device_group.html
