### ISSUE TITLE
NAT Rule Destination Address Translation Type

### ISSUE THREAD

**Issue by kerry-knight** [terraform-providers/terraform-provider-panos#25]
In AWS, trying to do a Nat Destination translation to an ELB which would have multiple addresses. It seems like I can't choose Destination Address Translation Type,   it defaults to the **Static IP**,  where I need **Dynamic IP ( with session distribution)** .  When I try to push from Terraform, with a  FQDN object, it errors out, which makes sense if you can't choose Dynamic. 

Is there a workaround, or a different way of accomplishing this?

**Comment by shinmog** [comment]
Selecting a dynamic destination address translation type is not yet supported, will be coming soon.

**Comment by shinmog** [comment]
@kerry-knight 
This is now added in the 1.2.0 provider.
