### ISSUE TITLE
Creating Panorama Services fails

### ISSUE THREAD

**Issue by kerry-knight** [terraform-providers/terraform-provider-panos#26]
It works properly for Shared Objects,  but can't put services into specific Device Groups. 

panos_panorama_service_object.tcp_1026: Could not find schema node for xpath /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='exampledg']/service

Was originally trying with nested Device groups, but all levels fail except for Shared. The Device Groups work properly for any manually created services.

**Comment by shinmog** [comment]
Yeah, this is a bug, I'll fix this in the next provider release.

**Comment by shinmog** [comment]
@kerry-knight 
This is now fixed in the 1.2.0 provider.
