### ISSUE TITLE
Feature Request:  IPSec Tunnels

### ISSUE THREAD

**Issue by shinmog** [terraform-providers/terraform-provider-panos#28]

**Comment by erikpaasonen** [comment]
Our use case for this is an industry standard "Transit VPC" pattern in AWS, with the Palo Altos protecting egress traffic originating from remote VPCs. The teams on the remote VPC are spinning up their VPN Connection resources using Terraform in a CI/CD pipeline. If we could auto respond to that automated event with automation of our own in Terraform to build the Palo Alto side of the IPSec tunnel, that would greatly improve the onboarding process - even possibly achieving "no touch" onboarding.

**Comment by kerry-knight** [comment]
For the "Transit VPC" pattern to work, we also would need the ability to Terraform the BGP portion of the setup.
