### ISSUE TITLE
Add Panorama Support

### ISSUE THREAD

**Issue by freimer** [terraform-providers/terraform-provider-panos#3]
All of our configuration on firewalls is performed through Panorama.  Please add Panorama support so we can specify the device group or template to which resources should be applied.

**Comment by lampwins** [comment]
I was thinking about this more and I want to throw something out there. I am not sure I want terraform to control state for my entire Panorama. I am thinking about this from a security policy standpoint. My Panorama might have thousands of policies covering dozens of use cases across many different device groups. I might not (don't) want _all_ of my device groups to be managed with terraform. I would, therefore, be in favor of Panorama support so long as the state can be limited to a device group at a time.

**Comment by shinmog** [comment]
I am thinking that the device group would be a parameter of the resource you're managing (e.g. - `vsys` for Address Objects).  So the provider would only touch the device groups you tell it to.

**Comment by shinmog** [comment]
This feature was added in the 1.1.0 release of the provider, available now.
