### ISSUE TITLE
Virtual Router - Static Routes

### ISSUE THREAD

**Issue by Pungyeon** [terraform-providers/terraform-provider-panos#30]
This is a request for adding functionality of adding static routes to virtual routers via. terraform panos. 

I suggets something like this:

```HCL
resource "panos_static_route" "sroute" {
    name = "default_route"
    destination = "0.0.0.0/0"
    interface = "${panos_ethernet_interface.ethernet1.name}"
    type = "ip-address" // (next-hop) (ip address | next vr | discard | none)
    value = "124.124.124.124" // whatever ip address
    admin_distance = "default" // or between 10 - 240
    metric = 10
    route_table = "unicast" // (unicast | multicast | both | no install)
}
```

I have left out path monitoring, as this is not something particularly necessary to be configurable. Of course, it's inclusion would be nice. I don't feel it's something that should halt the progress of implementing static routes though :)

Let me know if you would like assistance with implementation,

Thanks!

**Comment by stonefury** [comment]
We're deploying as well and just encountered this lacking feature. We'll have to do a work-around, maybe use paloalto's example terraform project which uses ansible, to do the static routes.
