### ISSUE TITLE
Feature Request: Document outputs of each resource

### ISSUE THREAD

**Issue by erikpaasonen** [terraform-providers/terraform-provider-panos#35]
Other Terraform providers with which I'm familiar provide documentation on each of the values that are output, but the `panos` provider does not seem to have any Outputs section in any of the resources. Prior to working with the `panos` provider I was unaware that Terraform Providers had a default set of outputs. It would assist us Terraform developers to include documentation in each resource type exactly which outputs can be expected, and their value types.

**Comment by shinmog** [comment]
Can you give an example please, @erikpaasonen ?

Generally speaking the outputs of a plan is something that you yourself ask Terraform to provide you (in the plan file).  Any parameter of a resource can be output, so anything can be an output.  I believe there is one exception to this:  resource params that are both `Optional: false` + `Required: false` + `Computed: true`:  these resources must be set by the provider, and cannot be set by the user in their plan files, but the `panos` provider does not (yet) have any of these style params.

**Comment by erikpaasonen** [comment]
Sorry @shinmog I'm probably mixing up terminology. I was referring to the attributes reference of what is output by a particular Terraform resource, as distinct from the input arguments. A great illustration can be found in Amazon's AWS Elastic IP (EIP) resource:

https://www.terraform.io/docs/providers/aws/r/eip.html

The resource documentation has a section defining the various arguments that are required and optional to request an EIP from Amazon. Notice how the Attributes Reference section lists different items than the Argument Reference section. The IP address value cannot be known by one of the inputs, so there is no input argument called `ip`, but there is an output attribute called `ip`.

The specific use case I've run into in the `panos` provider here is with `panos_ethernet_interface`. When I create an ethernet interface using DHCP, I don't have any way to predict the IP address given to the interface. But in order to create certain types of NAT rules, I need to specify the IP address of that interface as the value for a `panos_address_object`. Ideally there would be an additional attribute available above and beyond the input arguments that yields the IP address of the interface regardless of whether it was specified with static IPs or DHCP. Suggested syntax might be:
``` HCL
"${panos_ethernet_interface.example.ipv4_address}"
"${panos_ethernet_interface.example.ipv6_address}"
```

But this Issue was a more generic request to include an Attribute Reference section so that the syntax of all outputs of each resource is documented. Right now I feel like I have to guess-and-check what the attributes are.

**Comment by erikpaasonen** [comment]
@shinmog That's one specific example where there's a useful additional output attribute which is different from the input arguments. Perhaps the DHCP scenario belongs in a separate issue to address specifically. That separate issue would depend on this one, because without an `Attributes Reference` section there's no place to document the new attribute. This request was intended to be as generic as possible, to add the `Attributes Reference` section to all the `panos` resources.

I'm particularly interested if there is an `id` attribute on many of the `panos` resources such as `panos_address_object` and `panos_nat_rule`. Most Terraform resources appear to have an `id` but not sure if that applies in the `panos` resources. If they do have `id`, that could help with traceability concerns.

Another underlying question this documentation would solve is whether it's safe to assume that every available argument is also available as an attribute?

**Comment by shinmog** [comment]
@erikpaasonen 

I suspect that the `id` attribute on other provider's resources are the internal unique identifier for that particular resource.  In the case of PAN-OS, there is no separate internal unique identifier:  the unique identifier is (almost?) always the resource's name.  ...Well, technically, the unique identifier is a combination of the thing's location plus the thing's name.  An example of this would be address objects:  the unique identifier is the vsys where you say you want the address object to exist plus the name of the address object (said differently, there can only be one address object named `foo` in `vsys1`).

So as far as Attribute sections goes in the panos documentation, there aren't any attributes anywhere in the panos provider resources yet.  Going forward, I will make sure that if they are added, they are documented appropriately.  There are a few Attributes in the `panos_system_info` data source, but those are documented appropriately.

To answer your other question:  yes, you can freely access any resource's field to use in another resource's configuration, or place that field in an `output` block.  To stick with address objects, you could do this, and it would be fine:

```
resource "panos_address_object" "example" {
    name = "foo"
    vsys = "vsys1"
    ...
}

output "ao_example_vsys" {
    value = "${panos_address_object.example.vsys}"
}
```

I believe this only leaves "give me some way to get a data interface's DHCP info"..?  If you're ok with it, we could change the topic of this issue to add a data source to get an interface's DHCP client information, just let me know.
