### ISSUE TITLE
Trying to assign interface to zone, getting layer3 is invalid

### ISSUE THREAD

**Issue by stonefury** [terraform-providers/terraform-provider-panos#45]
I create an interface object, as layer3 as ethernet1/1

I can create the zone with layer3 just fine, but if I try to create the zone with layer3 and interfaces = ["ethernet1/1"] I get an error that layer3 is invalid.

So it doesn't seem possible to define an interface, and a zone, and associate the zone to the interface.

**Comment by shinmog** [comment]
I suspect you're not properly using dependencies.  You need to tell Terraform that the interface has to be created before trying to add it to your zone.  This works reliably for me:

```hcl
resource "panos_ethernet_interface" "eth" {
    name = "ethernet1/1"
    mode = "layer3"
    vsys = "vsys1"
}

resource "panos_zone" "z" {
    name = "my zone"
    mode = "layer3"
    interfaces = ["${panos_ethernet_interface.eth.name}"]
}
```

**Comment by stonefury** [comment]
@shinmog Thank you.  It worked.
