### ISSUE TITLE
Question: How to enable dependency on the VM?

### ISSUE THREAD

**Issue by stonefury** [terraform-providers/terraform-provider-panos#46]
Just looking or some guidance, or even useful if it were in the docs, regarding how to make the provider for panos depend on the VM for the vm-series.

tnx

**Comment by shinmog** [comment]
@stonefury 
Sorry, I'm not fully understanding your question.  The provider itself does not depend on only interacting with PAN-OS running on a VM, it can be a physical firewall (aka - many firewall resources take the `vsys` as an optional parameter, and vsys only exist on physical firewalls).

**Comment by shinmog** [comment]
Seems like maybe this isn't a question anymore..?  Closing the issue.
