### ISSUE TITLE
PANOS / Panorama Credentials File

### ISSUE THREAD

**Issue by freimer** [terraform-providers/terraform-provider-panos#5]
Please add the ability to use a "dotfile" like AWS provider, and pan-python, instead of using environment variables or Terraform variables for credentials.  Environment variables can be discoverable during the run.

**Comment by shinmog** [comment]
This feature was added in the 1.1.0 release of the provider, available now.

Credentials can now be given as a JSON file, allowing you to specify as many or as few of the provider connection parameters as you wish.  The locations checked for what a connection parameter should be is as follows (first one found to be non-empty wins):

1. the plan file
2. any non-empty default value (where applicable)
3. environment variable (where applicable)
4. the new JSON configuration file
