### ISSUE TITLE
Add "Virtual Router" and "Security Zone" option in panos_*_interface

### ISSUE THREAD

**Issue by Ceds-ALD** [terraform-providers/terraform-provider-panos#71]
Hi,

First of all, thank you for your work, it's very helpful!

I would love to have the possibility to assign an interface (Ethernet, VLAN, loopback, tunnel) to a "Virtual Router" and "Security Zone" from the panos_*_interface resource. Same as the "Assign Interface To" option in the web interface when one creates an interface.

Something like:

```hcl

resource "panos_tunnel_interface" "tunnel_int" {
  name           = "tunnel.${local.tunnel_number}"
  static_ips     = ["${panos_address_object.tunnelip.name}"]
  virtual_router = "${var.virtual_router_name}"
  zone           = "${panos_zone.zone.name}"
  comment        = "tf - Used for IPSEC"
}
```

My use case:

I want to use Terraform to create a Site-to-Site VPN between our network and dynamics infrastructure in Azure. 

So "terraform apply" will create the infrastructure in Azure and the VPN on site. 

To add a static route to the other side of the VPN I need to assign the tunnel.XX interface to our virtual router. But I don't want to manage the virtual router with Terraform as it is not only used for that specific use case and a "terraform "destroy would delete it.

Regards,

Cédric

**Comment by shinmog** [comment]
@Ceds-ALD 
Would it be acceptable if instead of making it part of a given `...interface` resource you would instead use an `entry` resource as I've been doing so far?  So something like this:

```hcl
resource "panos_virtual_router_interface_entry" "x" {
    virtual_router = "${var.virtual_router_name}"
    interface = "${panos_tunnel_interface.tunnel_int.name}"
}

resource "panos_zone_interface_entry" "x" {
    zone = "${panos_zone.zone.name}"
    interface = "${panos_tunnel_interface.tunnel_int.name}"
}
```

Using some kind of resource named `...entry` would fit with what exists so far (templates, template stacks).

**Comment by Ceds-ALD** [comment]
@shinmog 
Sure, it would achieve what I'm trying to do. If it better fit with what's already in place, by all means, go for that solution 😃

I'll only have to reference it in the panos_static_route_ipv4 to create a dependency.

```hcl
resource "panos_virtual_router_interface_entry" "x" {
    virtual_router = "${var.virtual_router_name}"
    interface = "${panos_tunnel_interface.tunnel_int.name}"
}

resource "panos_static_route_ipv4" "route" {
  name           = "${var.connection_name}_Route"
  virtual_router = "${var.virtual_router_name}"
  destination    = "${var.remote_networks}"
  type           = ""
  interface      =  "${panos_virtual_router_interface_entry.x.interface}"
}
```

Thanks,

Cédric

**Comment by erikpaasonen** [comment]
Our use case is also VPN setup. I'd just like to add, please don't neglect the Panorama flavored resources when implementing this. :) Thank you!

**Comment by erikpaasonen** [comment]
Any update on this issue? The absence of an `_entry` resource for adding a new interface to an existing zone is turning out to be a huge blocker for our team.

**Comment by shinmog** [comment]
@Ceds-ALD 

This workflow is supported in the new 1.4.1 provider.

**Comment by selman-neudesic** [comment]
How can we delete the specific interface in a zone?

**Comment by AnujSehgall** [comment]
How can we delete  one interface from a zone and attach to another existing zone?
