### ISSUE TITLE
Unable to reference ethernet interface created by different template

### ISSUE THREAD

**Issue by erikpaasonen** [terraform-providers/terraform-provider-panos#75]
### Terraform Version
```
Terraform v0.11.8
+ provider.panos v1.4.0
```

### Terraform Configuration Files
We are using IKE and IPSec resources to reproduce this error, but a zone is a simpler resource to illustrate this issue.
```hcl
resource "panos_panorama_template" "tmpl1" {
  name = "MyInfrastructureTemplate"
}

resource "panos_panorama_template" "tmpl2" {
  name = "MyLocationSpecificTemplate"
}

resource "panos_panorama_ethernet_interface" "example1" {
    name = "ethernet1/1"
    template = "${panos_panorama_template.tmpl1.name}"
    mode = "layer3"
    enable_dhcp = "true"
}

resource "panos_panorama_zone" "example2" {
    name = "my_zone"
    template = "${panos_panorama_template.tmpl2.name}"
    mode = "layer3"
    interfaces = ["${panos_panorama_ethernet_interface.example1.name}"]
}
```

### Expected Behavior
``` hcl
panos_panorama_template.tmpl2: Creating...
  default_vsys: "" => "<computed>"
  devices.#:    "" => "<computed>"
  name:         "" => "MyOtherTemplate"
panos_panorama_template.tmpl1: Creating...
  default_vsys: "" => "<computed>"
  devices.#:    "" => "<computed>"
  name:         "" => "MyTemplate"
panos_panorama_template.tmpl1: Creation complete after 1s (ID: MyTemplate)
panos_panorama_ethernet_interface.example1: Creating...
  create_dhcp_default_route: "" => "true"
  dhcp_default_route_metric: "" => "10"
  enable_dhcp:               "" => "true"
  mode:                      "" => "layer3"
  name:                      "" => "ethernet1/1"
  template:                  "" => "MyTemplate"
  vsys:                      "" => "vsys1"
panos_panorama_template.tmpl2: Creation complete after 1s (ID: MyOtherTemplate)
panos_panorama_ethernet_interface.example1: Creation complete after 0s (ID: MyTemplate::vsys1:ethernet1/1)
panos_panorama_zone.example2: Creating...
  interfaces.#: "" => "1"
  interfaces.0: "" => "ethernet1/1"
  mode:         "" => "layer3"
  name:         "" => "my_zone"
  template:     "" => "MyOtherTemplate"
  vsys:         "" => "vsys1"

Apply complete! Resources: 4 added, 0 changed, 0 destroyed.
```

### Actual Behavior
``` hcl
panos_panorama_template.tmpl2: Creating...
  default_vsys: "" => "<computed>"
  devices.#:    "" => "<computed>"
  name:         "" => "MyOtherTemplate"
panos_panorama_template.tmpl1: Creating...
  default_vsys: "" => "<computed>"
  devices.#:    "" => "<computed>"
  name:         "" => "MyTemplate"
panos_panorama_template.tmpl1: Creation complete after 1s (ID: MyTemplate)
panos_panorama_ethernet_interface.example1: Creating...
  create_dhcp_default_route: "" => "true"
  dhcp_default_route_metric: "" => "10"
  enable_dhcp:               "" => "true"
  mode:                      "" => "layer3"
  name:                      "" => "ethernet1/1"
  template:                  "" => "MyTemplate"
  vsys:                      "" => "vsys1"
panos_panorama_template.tmpl2: Creation complete after 1s (ID: MyOtherTemplate)
panos_panorama_ethernet_interface.example1: Creation complete after 0s (ID: MyTemplate::vsys1:ethernet1/1)
panos_panorama_zone.example2: Creating...
  interfaces.#: "" => "1"
  interfaces.0: "" => "ethernet1/1"
  mode:         "" => "layer3"
  name:         "" => "my_zone"
  template:     "" => "MyOtherTemplate"
  vsys:         "" => "vsys1"

Error: Error applying plan:

1 error(s) occurred:

* panos_panorama_zone.example2: 1 error(s) occurred:

* panos_panorama_zone.example2:  vsys -> vsys1 -> zone -> my_zone -> network -> layer3 is invalid

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Steps to Reproduce
1. Set up .tf file with the above quoted code and configure a `panos` provider in a temp dir
1. `terraform init`
1. `terraform apply`

If you change the template of `panos_panorama_zone.example2` to match the same template as the one which creates the ethernet interface (`template = "${panos_panorama_template.tmpl1.name}"`), then everything applies successfully.

### Additional Context
It appears that certain networking resources are required to be created within the same template as where they are referenced. Our intuitive template hierarchy separates the creation of ethernet interfaces away from the setup of VPN tunnels that will use that interface, so that we can modularize the VPN tunnel setup. If the Panorama template ecosystem is designed in such a way that we cannot separate these, then we will need several more data sources to be made available in the `panos` provider so that we can lookup the needed values (e.g. the name of an ethernet interface created by an infrastructure template).

This may be obvious to someone more experienced with the Palo Alto Networks ecosystem, but it was a struggle to figure out based on the given error message that the root cause here was actually a template mismatch.

**Comment by erikpaasonen** [comment]
I should note, we tried including all relevant templates in a template stack thinking that would provide enough context for Terraform to figure out how to get to the ethernet interface, but it still produced the same error behavior.

We were unable to reproduce this issue with the `panos_*` flavored resources, likely because the issue is template scoping (which we admittedly don't fully understand - yet!).

**Comment by shinmog** [comment]
@erikpaasonen 

As you guessed, Template config has to be self-contained, to a certain extent.  You can't have Template 1's interface referenced by Template 2's zone.  If you tried to do this in the Panorama GUI, you would see that the interfaces that are in Template 1 would not be visible to Template 2's zone in the interface dropdown.

**Comment by erikpaasonen** [comment]
Ok, our inexperience with the Panorama platform was showing here. Closing this issue as it appears to be working as designed. We'll design our template/template stack inheritance around this.
