### ISSUE TITLE
Feature Request: subinterface creation

### ISSUE THREAD

**Issue by chewdevs** [terraform-providers/terraform-provider-panos#82]
The `panos_ethernet_interface` resource does not permit to create subinterface. 

The use case is the ability to create subinterface for VLAN tagging when the parent interface is configured as a trunk.

**Comment by shinmog** [comment]
@chewdevs 
Ok - this will likely be implemented as two separate resources, as L2 subinterfaces have different params from L3 subinterfaces.

**Comment by Ricomlb123** [comment]
We need sub-interface support to provision on premises firewall for DirectConnect PVI !

**Comment by raypettersen** [comment]
We also need sub-interface creation, or is there another way to tie vlans to a physical interface? This is quite important for us for making the leap from another firewall brand to Palo.

**Comment by shinmog** [comment]
@raypettersen 

I've opened #145 and #146 for VLAN related functionality.

**Comment by raypettersen** [comment]
Thanks @shinmog!

**Comment by pryorda** [comment]
@shinmog is there an ETA for this. It is currently blocking us from almost completely codified firewalls.

**Comment by shinmog** [comment]
This will be in the next release for sure, I don't have an ETA for it, however.

**Comment by FrederikWal** [comment]
Would be nice for us also, looking forward to the next release with this feature included.

**Comment by danielvels** [comment]
We also need to create subinterfaces in terraform to be able to automate our BGP peerings from On-Prem to AWS.

**Comment by shinmog** [comment]
@chewdevs @Ricomlb123 @raypettersen @pryorda @FrederikWal @danielvels 

I'm going to be adding subinterfaces for L2 and L3 ethernet interfaces.  Do any of you need this for aggregate interfaces as well?

**Comment by rfc1149** [comment]
I would definitely need subinterfaces for aggregate interfaces!

**Comment by danielvels** [comment]
Yes, we use multiple physical lines as one aggregated line. On this line we create our sub interfaces we use in our peer config.

**Comment by raypettersen** [comment]
@shinmog great! This will make a huge difference for us in getting everything into terraform. Can't wait :-)
